### ISSUE TITLE
文档里为什么没有数据库的说明？

### ISSUE THREAD

**Issue by Dreamseekai** [zendframework/zend-permissions-rbac#27]
Why no databases documents for rbac

**Comment by Ocramius** [comment]
This module provides no DB integration - DB integration is to be implemented by implementing a custom https://github.com/zendframework/zend-permissions-rbac/blob/98252acae03f52e83e937150efe81f621e15891c/src/Rbac.php that reads from the DB instead of performing in-memory operations.

Closing as duplicate of https://github.com/zendframework/zend-permissions-rbac/issues/28
