### ISSUE TITLE
3.0.1 broken

### ISSUE THREAD

**Issue by brouardt** [zendframework/zend-permissions-rbac#40]
In this version, the RoleInterface declare Iterable return type for the methods getChildrens() and getParents() but the "Role" Class return array for them.

**Comment by ezimuel** [comment]
This is not broken thanks to [Iterable Type Variant](http://php.net/manual/en/language.types.iterable.php#language.types.iterable.variance) of PHP. Array is a valid iterable type.

**Comment by weierophinney** [comment]
Did you observe an error? If so:

- What version of PHP were you using?
- What are the error details?

The reason I ask is because we tested this in the versions of PHP the 3.0 releases support (7.1+). In those versions, this practice works. Why? Because return values in PHP are [covariant](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Covariant_method_return_type). This means you can use a _more specific_ typehint in implementations/extensions.

**Comment by brouardt** [comment]
I know Iterable is compatible with Array. 
But :
PHP Fatal error:  Declaration of Zend\\Permissions\\Rbac\\Role::getParents(): array must be compatible with Zend\\Permissions\\Rbac\\RoleInterface::getParents(): Zend\\Permissions\\Rbac\\iterable in /home/src/staging/api.database.webengineering.fr/1-0-85-ADWF-149/vendor/zendframework/zend-permissions-rbac/src/Role.php on line 12

**Comment by weierophinney** [comment]
@brouardt There's something funky with the above, as it's indicating `Zend\Permissions\Rbac\iterable` as the typehint in the error; it should just be `iterable`. I don't think the PHP version is what you're reporting it is.

@Ocramius Return types are covariant as of 7.1: https://3v4l.org/Fa5id

**Comment by Ocramius** [comment]
Ah, so the code is probably running on 7.0 then...

**Comment by Ocramius** [comment]
Closing here as per https://github.com/zendframework/zend-permissions-rbac/issues/40#issuecomment-416626566

@brouardt please make sure you are running 7.1+.

**Comment by brouardt** [comment]
You have definitely right. What a shame, our server is normaly PHP-FPM, but It use php7_module. Where is the system admin. I will .... him

=> PHP Version 7.0.31-1+0~20180725100316.2+stretch~1.gbp8e8a8b 

Thanks for your help.
